#pom=pom.xml
#pom.web=pom-web.xml
#pom.all-in-one=pom-all-in-one.xml
example.core.default=egovframe-mobile-core.zip
example.core.optional=
example.web.default=egovframe-mobile-web.zip
example.web.optional=egovframe-mobile-core.zip
example.allinone=egovframe-mobile-common-components.zip