txtAppenderName=appender1
txtLogFileName=./logs/time/timeBasedRollingSample.log
txtLogFileNamePattern=./logs/time/timeBasedRollingSample.%d{yyyy-MM-dd_HH-mm}.log
txtInterval=1
cboModulate=true
txtConversionPattern=%d %5p [%c] %m%n
