#pom=pom.xml
pom.core=pom-core.xml
pom.web=pom-web.xml
#pom.portal=pom-template-portal.xml
#pom.enterprise=pom-template-enterprise.xml
#pom.simple=pom-template-simple.xml
#pom.common=pom-template-common.xml
example.core.default=egovframe-core.zip
example.core.optional=
example.web.default=egovframe-web.zip
example.web.optional=govframe-core.zip
example.template.portal=egovframe-template-portal.zip
example.template.enterprise=egovframe-template-enterprise.zip
example.template.simple=egovframe-template-simple.zip
example.template.common=egovframe-template-common-components.zip