txtTransactionName=tran1
txtEttMgrFactory=factory1
txtPstUnitName=unit1
txtPstXMLLoc=classpath:/xml/
txtDataSourceName=ds1
txtPackagesToScan=egovframework.sample
cmbDialect=org.hibernate.dialect.H2Dialect
txtSpringDataJPAPackage=egovframework.sample.repository
chkAnnotationTransactionManagement=true
chkRollbackFor=true
cmbIsolation=DEFAULT
cmbPropagation=REQUIRED
txtAdviceName=txAdvice
txtMethodName=*
txtPointCutExpression=execution(* egovframework.sample..*Impl.*(..))
txtPointCutName=requiredTx
txtRollbackFor=Exception
