txtDatasourceName=ds1
txtJndiName=jndi1
cboResourceRef=true
txtInitialFactory=factory
txtProviderUrl=http://localhost/
txtTransactionName=tran1
txtGlobalTimeout=20
chkAnnotationTransactionManagement=true
chkRollbackFor=true
cmbIsolation=DEFAULT
cmbPropagation=REQUIRED
txtAdviceName=txAdvice
txtMethodName=*
txtPointCutExpression=execution(* egovframework.com..*Impl.*(..)) or execution(* org.egovframe.rte.fdl.excel.impl.*Impl.*(..))
txtPointCutName=requiredTx
txtRollbackFor=Exception
