txtTransactionName=tran1
txtDatasourceName=ds1
chkTransactionTemplate=true
txtTransactionTemplateName=transactionTemplate
chkConfigurationalTransactionManagement=true
txtPointCutName=requiredTx
txtPointCutExpression=execution(* egovframework.sample..*Impl.*(..))
txtAdviceName=txAdvice
txtMethodName=*
chkRollbackFor=true
txtRollbackFor=Exception
chkTimeout=true
txtTimeout=20
cmbPropagation=REQUIRED
cmbIsolation=DEFAULT
chkAnnotationTransactionManagement=true
